logout:
    path:     /logout
    defaults: { _controller: CreativerFrontBundle:Default:main }
    methods:  [GET]
creativer_front_registration:
    path:     /registration
    defaults: { _controller: CreativerFrontBundle:Default:registration }
creativer_front_forgot_password:
    path:     /forgot_password
    defaults: { _controller: CreativerFrontBundle:Default:forgotPassword }
creativer_front_main:
    path:     /
    defaults: { _controller: CreativerFrontBundle:Default:layout_front }
security_check:
    path:     /security_check
    defaults: { _controller: CreativerFrontBundle:Default:security_check }
person:
    path:     /
    defaults: { _controller: CreativerFrontBundle:Default:layout_front }
    methods:  [GET]
creativer_peopleTmp:
    path:     /people_tmp
    defaults: { _controller: CreativerFrontBundle:Default:peopleTmp }
    methods:  [GET]
creativer_searchEventsTmp:
    path:     /search_events_tmp
    defaults: { _controller: CreativerFrontBundle:Default:searchEventsTmp }
    methods:  [GET]
creativer_mainTmp:
    path:     /main_tmp
    defaults: { _controller: CreativerFrontBundle:Default:mainTmp }
    methods:  [GET]
creativer_productsTmp:
    path:     /products_tmp
    defaults: { _controller: CreativerFrontBundle:Default:productsTmp }
    methods:  [GET]
creativer_servicesTmp:
    path:     /services_tmp
    defaults: { _controller: CreativerFrontBundle:Default:servicesTmp }
    methods:  [GET]
creativer_personTmp:
    path:     /person_tmp/{id}
    defaults: { _controller: CreativerFrontBundle:Default:personTmp, id: null }
    methods:  [GET]
creativer_showPhotoTmp:
    path:     /show_photo_tmp
    defaults: { _controller: CreativerFrontBundle:Default:showPhotoTmp }
    methods:  [GET]
creativer_showPostPhotoTmp:
    path:     /show_post_photo_tmp
    defaults: { _controller: CreativerFrontBundle:Default:showPostPhotoTmp }
    methods:  [GET]
creativer_showProductPhotoTmp:
    path:     /show_product_photo_tmp
    defaults: { _controller: CreativerFrontBundle:Default:showProductPhotoTmp }
    methods:  [GET]
creativer_baraholkaTmp:
    path:     /baraholka_tmp
    defaults: { _controller: CreativerFrontBundle:Default:baraholkaTmp }
    methods:  [GET]
creativer_eventsTmp:
    path:     /events_tmp
    defaults: { _controller: CreativerFrontBundle:Default:eventsTmp }
    methods:  [GET]
creativer_eventTmp:
    path:     /event_tmp
    defaults: { _controller: CreativerFrontBundle:Default:eventTmp }
    methods:  [GET]
creativer_create_eventTmp:
    path:     /create_event_tmp/{date}
    defaults: { _controller: CreativerFrontBundle:Default:createEventTmp, date: null }
    methods:  [GET]
creativer_edit_eventTmp:
    path:     /edit_event_tmp
    defaults: { _controller: CreativerFrontBundle:Default:editEventTmp }
    methods:  [GET]
creativer_fleamarketpostingTmp:
    path:     /fleamarketposting_tmp
    defaults: { _controller: CreativerFrontBundle:Default:fleamarketpostingTmp }
    methods:  [GET]
creativer_editFleamarketpostingTmp:
    path:     /edit_fleamarketposting_tmp
    defaults: { _controller: CreativerFrontBundle:Default:editFleamarketpostingTmp }
    methods:  [GET]
creativer_shopsTmp:
    path:     /shops_tmp
    defaults: { _controller: CreativerFrontBundle:Default:shopsTmp }
    methods:  [GET]
creativer_create_shopTmp:
    path:     /create_shop_tmp
    defaults: { _controller: CreativerFrontBundle:Default:createShopTmp }
    methods:  [GET]
creativer_viewforumTmp:
    path:     /viewforum_tmp
    defaults: { _controller: CreativerFrontBundle:Default:viewforumTmp }
    methods:  [GET]
creativer_viewtopicTmp:
    path:     /viewtopic_tmp
    defaults: { _controller: CreativerFrontBundle:Default:viewtopicTmp }
    methods:  [GET]
creativer_messagesTmp:
    path:     /messages_tmp
    defaults: { _controller: CreativerFrontBundle:Default:messagesTmp }
    methods:  [GET]
creativer_chatTmp:
    path:     /chat_tmp
    defaults: { _controller: CreativerFrontBundle:Default:chatTmp }
    methods:  [GET]
creativer_feedbackTmp:
    path:     /feedback_tmp
    defaults: { _controller: CreativerFrontBundle:Default:feedbackTmp }
    methods:  [GET]
creativer_createPostBaraholka:
    path:     /createPostBaraholka
    defaults: { _controller: CreativerFrontBundle:Default:createPostBaraholka }
    methods:  [POST]
creativer_front_create_albumTmp:
    path:     /create_album
    defaults: { _controller: CreativerFrontBundle:Default:createAlbumTmp }
    methods:  [GET]
creativer_front_edit_albumTmp:
    path:     /edit_album
    defaults: { _controller: CreativerFrontBundle:Default:editAlbumTmp }
    methods:  [GET]
creativer_front_albumTmp:
    path:     /album_tmp/{id_album}
    defaults: { _controller: CreativerFrontBundle:Default:albumTmp, id_album: null }
    methods:  [GET]
creativer_front_followingTmp:
    path:     /following_tmp/{id}
    defaults: { _controller: CreativerFrontBundle:Default:followingTmp, id: null }
    methods:  [GET]
creativer_front_followersTmp:
    path:     /followers_tmp/{id}
    defaults: { _controller: CreativerFrontBundle:Default:followersTmp, id: null }
    methods:  [GET]
creativer_front_upload_album:
    path:     /upload_album
    defaults: { _controller: CreativerFrontBundle:Default:uploadAlbum }
    methods:  [POST]
creativer_front_upload_shop:
    path:     /upload_shop
    defaults: { _controller: CreativerFrontBundle:Default:uploadShop }
    methods:  [POST]
creativer_front_upload_edit_album:
    path:     /upload_edit_album
    defaults: { _controller: CreativerFrontBundle:Default:uploadEditAlbum }
    methods:  [POST]
creativer_upload_image_event:
    path:     /upload_image_event
    defaults: { _controller: CreativerFrontBundle:Default:uploadImageEvent }
    methods:  [POST]
creativer_create_post_baraholka:
    path:     /create_post_baraholka
    defaults: { _controller: CreativerFrontBundle:Default:createPostBaraholka }
    methods:  [POST]
creativer_edit_images_post_baraholka:
    path:     /edit_images_post_baraholka
    defaults: { _controller: CreativerFrontBundle:Default:editImagesPostBaraholka }
    methods:  [POST]
creativer_save_post_images:
    path:     /save_post_images
    defaults: { _controller: CreativerFrontBundle:Default:savePostImages }
    methods:  [POST]