logout:
    path:     /logout
    defaults: { _controller: CreativerFrontBundle:Default:main }
    methods:  [GET]
creativer_front_registration:
    path:     /registration
    defaults: { _controller: CreativerFrontBundle:Default:registration }
creativer_front_main:
    path:     /
    defaults: { _controller: CreativerFrontBundle:Default:layout_front }
security_check:
    path:     /security_check
    defaults: { _controller: CreativerFrontBundle:Default:security_check }
person:
    path:     /
    defaults: { _controller: CreativerFrontBundle:Default:layout_front }
    methods:  [GET]
creativer_mainTmp:
    path:     /main_tmp
    defaults: { _controller: CreativerFrontBundle:Default:mainTmp }
    methods:  [GET]
creativer_productsTmp:
    path:     /products_tmp
    defaults: { _controller: CreativerFrontBundle:Default:productsTmp }
    methods:  [GET]
creativer_servicesTmp:
    path:     /services_tmp
    defaults: { _controller: CreativerFrontBundle:Default:servicesTmp }
    methods:  [GET]
creativer_personTmp:
    path:     /person_tmp/{id}
    defaults: { _controller: CreativerFrontBundle:Default:personTmp, id: null }
    methods:  [GET]
creativer_baraholkaTmp:
    path:     /baraholka_tmp
    defaults: { _controller: CreativerFrontBundle:Default:baraholkaTmp }
    methods:  [GET]
creativer_fleamarketpostingTmp:
    path:     /fleamarketposting_tmp
    defaults: { _controller: CreativerFrontBundle:Default:fleamarketpostingTmp }
    methods:  [GET]
creativer_viewforumTmp:
    path:     /viewforum_tmp
    defaults: { _controller: CreativerFrontBundle:Default:viewforumTmp }
    methods:  [GET]
creativer_viewtopicTmp:
    path:     /viewtopic_tmp
    defaults: { _controller: CreativerFrontBundle:Default:viewtopicTmp }
    methods:  [GET]
creativer_messagesTmp:
    path:     /messages_tmp
    defaults: { _controller: CreativerFrontBundle:Default:messagesTmp }
    methods:  [GET]
creativer_chatTmp:
    path:     /chat_tmp
    defaults: { _controller: CreativerFrontBundle:Default:chatTmp }
    methods:  [GET]
creativer_feedbackTmp:
    path:     /feedback_tmp
    defaults: { _controller: CreativerFrontBundle:Default:feedbackTmp }
    methods:  [GET]
creativer_createPostBaraholka:
    path:     /createPostBaraholka
    defaults: { _controller: CreativerFrontBundle:Default:createPostBaraholka }
    methods:  [POST]
creativer_front_create_albumTmp:
    path:     /create_album
    defaults: { _controller: CreativerFrontBundle:Default:createAlbumTmp }
    methods:  [GET]
creativer_front_edit_albumTmp:
    path:     /edit_album
    defaults: { _controller: CreativerFrontBundle:Default:editAlbumTmp }
    methods:  [GET]
creativer_front_albumTmp:
    path:     /album_tmp/{id_album}
    defaults: { _controller: CreativerFrontBundle:Default:albumTmp, id_album: null }
    methods:  [GET]
creativer_front_favoritTmp:
    path:     /favorit_tmp
    defaults: { _controller: CreativerFrontBundle:Default:favoritTmp }
    methods:  [GET]
creativer_front_upload_album:
    path:     /upload_album
    defaults: { _controller: CreativerFrontBundle:Default:uploadAlbum }
    methods:  [POST]
creativer_front_upload_edit_album:
    path:     /upload_edit_album
    defaults: { _controller: CreativerFrontBundle:Default:uploadEditAlbum }
    methods:  [POST]
creativer_create_post_baraholka:
    path:     /create_post_baraholka
    defaults: { _controller: CreativerFrontBundle:Default:createPostBaraholka }
    methods:  [POST]
