services:
#    my.handler.session_idle:
#        class: Creativer\FrontBundle\Handler\SessionIdleHandler
#        arguments: ["@session", "@security.context", "@router", %session_max_idle_time%]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    kernel.listener.response_listener:
        class: Creativer\FrontBundle\Handler\ResponseListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    session_handler_redis:
        class: Creativer\FrontBundle\Handler\NativeRedisSessionHandler
        arguments:    ["%session_handler_redis_save_path%"]
    my_service:
        class: Creativer\FrontBundle\Services\ImageServices
        arguments: ['@service_container']
    your.twig.extension:
        class: Creativer\FrontBundle\Twig\twigExtension
        tags:
            -  { name: twig.extension }
    google.client:
        class: Creativer\FrontBundle\Handler\Google
        arguments: ['https://www.googleapis.com/auth/calendar.readonly']
    ib_user.oauth_user_provider:
        class: Creativer\FrontBundle\Handler\Provider
        arguments: ['@doctrine','@service_container']
#    my_user_provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
#        arguments:
#            userManager: "@fos_user.user_manager"
#            arguments: [ @fos_user.user_manager, { facebook: facebook_id, vkontakte: vkontakte_id } ]
#    instant_mailer:
#        class: %swiftmailer.class%
#        arguments: ["@?swiftmailer.transport.real"]
#    fos_elastica.listener.app.album:
#        class: Creativer\FrontBundle\Handler\ElasticaCourseListener
#        arguments:
#            - '@fos_elastica.object_persister.app.album'
#            - ['postPersist', 'postUpdate', 'postRemove', 'preRemove']
#            - @fos_elastica.indexable
#        calls:
#             - [ setContainer, ['@service_container', @fos_elastica.object_persister.app.images ] ]
#        tags:
#            - { name: 'doctrine.event_subscriber' }