elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

creativer_background:
    resource: "@CreativerBackgroundBundle/Controller/"
    type:     annotation
    prefix:   /

creativer_front:
    resource: "@CreativerFrontBundle/Resources/config/routing.yml"
    prefix:   /

creativer_api:
    resource: "@CreativerApiBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

vkontakte_login:
    path: /login/check-vkontakte

facebook_login:
    path: /login/check-facebook

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

