creativer_background:
    resource: "@CreativerBackgroundBundle/Controller/"
    type:     annotation
    prefix:   /

creativer_front:
    resource: "@CreativerFrontBundle/Resources/config/routing.yml"
    prefix:   /

creativer_api:
    resource: "@CreativerApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
