security:
    encoders:
        Creativer\FrontBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [our_db_provider, user_db]
        user_db:
            id: ib_user.oauth_user_provider
        our_db_provider:
            entity:
                class: CreativerFrontBundle:User
                property: email

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            remember_me:
                key: divine_office_hub_1234567
                lifetime: 31536000
                always_remember_me: true
                path: /
                domain: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                check_path: /security_check
                login_path: /
                username_parameter: email
                password_parameter: password
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            oauth:
                 resource_owners:
                    facebook: "/login/check-facebook"
                    vkontakte: "/login/check-vkontakte"
                 login_path: /
                 failure_path: /
                 oauth_user_provider:
    #                     HWIOAuthBundle ???????????? ? ????? ???????????? ?? ?????????:
    #                     OAuthUserProvider (????????? ????????: hwi_oauth.user.provider) - ?????? ?? ????????? ?????????????
    #                     EntityUserProvider (????????? ????????: hwi_oauth.user.provider.entity) - ????????? ????????????? ?? ???? ??????
    #                     FOSUserBundle ?????????? (????????? ????????: hwi_oauth.user.provider.fosub_bridge).
                      service: ib_user.oauth_user_provider
#        main:
#            pattern: ^/
#            anonymous: true
#            logout: true
#            logout:
#                path:   /logout
#                target: /

    access_control:
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
#        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
