security:
    encoders:
        Creativer\FrontBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
            entity:
                class: CreativerFrontBundle:User
                property: email

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                check_path: /security_check
                login_path: /
                username_parameter: email
                password_parameter: password
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
#        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
