<?php

namespace Creativer\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends EntityRepository
{

    public function searchCatalogProduct()
    {


//        $items = $this->getEntityManager()->getRepository('CreativerFrontBundle:Categories')->findBy(array('id'=>86));
//
//        $i = 0;
//        while(isset($items[$i])){
//            if(!$items[$i]->getChildren()->isEmpty()){
//                $childs = $items[$i]->getChildren();
//
//                foreach($childs as $k => $v) {
//                    array_push($items, $childs[$k]);
//                }
//            }
//            $i++;
//        }

            $query = $this->getEntityManager()->getRepository('CreativerFrontBundle:Images')
                ->createQueryBuilder('e')
                ->select('cat.id as id_cat', 'e.id','e.name','alb.id as id_album','alb.name as name_album','usr.id as id_user','usr.username','usr.lastname','e.likes','e.views','e.date')
                ->leftJoin('e.album', 'alb')
                ->leftJoin('alb.user', 'usr')
                ->leftJoin('alb.categories', 'cat')
                ->where('cat IN (:items)')
                ->setParameter('items', array(86));


            return $query;



    }
}
